services:

  sqlserver:
    container_name: clynic-sql
    build:
      context: .
      dockerfile: docker/sqlserver/Dockerfile

    environment:
      SA_PASSWORD: "${SQL_SA_PASSWORD:?Set SQL_SA_PASSWORD in .env}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"

    ports:
      - "${DB_PORT:-1433}:1433"

    volumes:
      - sql_data:/var/opt/mssql

    networks:
      - clynic-network

    healthcheck:
      test: ["CMD", "ps", "aux"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 50s


  api:
    container_name: clynic-api
    build:
      context: .
      dockerfile: Clynic.Api/Dockerfile

    ports:
      - "${API_PORT:-8080}:8080"

    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=${SQL_DATABASE};User Id=${SQL_USER};Password=${SQL_SA_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=true;
      - ASPNETCORE_ENVIRONMENT=Development

    depends_on:
      sqlserver:
        condition: service_healthy

    networks:
      - clynic-network

    restart: on-failure


volumes:
  sql_data:

networks:
  clynic-network:
